### ISSUE TITLE
High symmetry of MOLFDIR also for Dirac ?

### ISSUE THREAD

**Issue by miroi** [MOLFDIR/MOLFDIR#1]
Dear Luuk,

MOLFDIR works with higher (double group) symmetries, allowing thus better description of states. Example, FO - molecule - there are 2 fermion irreps, one for 2Pi1/2, another for 2Pi3/2. In Dirac it's quite difficult to get both states in Cinfv (I have tried).

The question is : could MOLFDIR scf outputs (MOs) of high symmetry be passed into Dirac MO-transformation and subsequent correlation machinery (relcc, luciarel etc) ?

**Comment by LucasVisscher** [comment]
Interesting point, the underlying symmetry for the symmetry functions is indeed higher for MOLFDIR even though the final supersymmetry that is used is higher in DIRAC. Matching the two is difficult and probably better handled (and discussed) on the DIRAC side.

**Comment by LucasVisscher** [comment]
Discussion will be continued within the DIRAC community
